### ISSUE TITLE
Problèmes sur la delevop (Linux)

### ISSUE THREAD

**Issue by Anard** [BoboTiG/pombo#19]
Bonjour,
J'ai voulu essayer d'utiliser la branche develop pour mes modifications mais : 
 - J'ai dû réutiliser l'ancien système pour les screenshots qui ne fonctionnent pas dans la nouvelle version
En fait, python bugue à
`import mss` qu'il n'arrive pas à trouver, voici la réponse quand je lances pombo : 
> no module named mss

Quand je cherche à l'installer, j'obtiens : 
> Requirement already satisfied : mss in /usr/local/lib/python3.6/dist-packages

 - Il rencontre toujours une erreur (mauvais chemin apparemment) dans la création du rapport : 
`[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/usr/local/bin/pombo", line 1051, in <module>
    exit(main(sys.argv))
  File "/usr/local/bin/pombo", line 1040, in main
    pombo.work()
  File "/usr/local/bin/pombo", line 933, in work
    self.snapshot(current_ip)
  File "/usr/local/bin/pombo", line 723, in snapshot
    fileh.write(os.path.basename(filepath))
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: ''`

**Comment by Anard** [comment]
OK.
Mon système utilisait la version 2.7 de Python par défaut alors que la 3.6 était installée à côté avec tous les modules.
J'ai donc mis à jour mes corrections.
