### ISSUE TITLE
Error Pombo - test.bat

### ISSUE THREAD

**Issue by maitrey0da** [BoboTiG/pombo#6]
Bonjour,

Pombo soulève une erreur. Ci-dessous, l'erreur (désolé pour le formatage, c'est du Windows)

```
C:\pombo>"Pombo - Test.bat"
Pombo 1.0.3
[Test] Simulating stolen computer ...
Retrieving IP address from www.xx.com
Starting new HTTP connection (1): www.xx.com
"GET /pombo.php?myip=1 HTTP/1.1" 200 None
Content: 1xxxxx6
Filename: vm-xxxxx_20160503_144409
Collecting system info
Using Python 2.7.5
wmic csproduct get vendor, name, version /value & useshell=True
Manufacturer is innotek GmbH - VirtualBox - 1.2
wmic bios get serialnumber /value & useshell=True
Serial number is Unknown
System report: network_config()
['ipconfig', '/all'] & useshell=False
System report: wifi_access_points()
['netsh', 'wlan', 'show', 'all'] & useshell=False
System report: traceroute()
['tracert', '-d', 'www.xxxxx.fr'] & useshell=False
System report: network_trafic()
['netstat', '-n'] & useshell=False
Taking screenshot
Skipping webcamshot.
Zipping files
Encrypting zip with GnuPG
['C:ombo\\binpg.exe', '--batch', '--no-default-keyring', '--trust-model', 'alway
s', '-r', 'xxxxxx', '-o', 'c:\\users\\xxxxxx\\appdata\\local\\temp\\vm-maitr
eyoda_20160503_144409.zip.gpg', '-e', 'c:\\users\\xxxxx\\appdata\\local\\temp
\\vm-xxxxx_20160503_144409.zip'] & useshell=False
[Error 2] Le fichier sp�cifi� est introuvable
Traceback (most recent call last):
  File "pombo.py", line 887, in <module>
    sys.exit(main(sys.argv))
  File "pombo.py", line 876, in main
    pombo.work()
  File "pombo.py", line 745, in work
    self.snapshot(current_ip)
  File "pombo.py", line 602, in snapshot
    gpgfilepath, '-e', zipfilepath])
  File "pombo.py", line 454, in runprocess
    shell=useshell)
  File "C:\pombo\python\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\pombo\python\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] Le fichier sp�cifi� est introuvable


Appuyez sur une touche pour continuer...%     
```                     
Il s'agit d'un Windows 8 avec gpg en version 2.0.30

Le fichier «vm-maitreyoda_20160503_144409.zip» existe bien

Merci

**Comment by Kinae** [comment]
D'après l'erreur le fichier qu'il essaye de ZIP n'existe pas. Peux-tu vérifier manuellement ?

c:\\users\\xxxxx\\appdata\\local\\temp\\vm-xxxxx_20160503_144409.zip

**Comment by maitrey0da** [comment]
Sisi il existe 

```
C:\Users\xxx\AppData\Local\Temp>dir *.zip
 Le volume dans le lecteur C n'a pas de nom.
 Le num�ro de s�rie du volume est BC0D-2D8B

 R�pertoire de C:\Users\xxxx\AppData\Local\Temp

20/04/2016  12:47            60�411 vm-xx_20160420_124704.zip
20/04/2016  12:52           113�753 vm-xx_20160420_125211.zip
20/04/2016  14:11           267�733 vm-xx_20160420_141110.zip
03/05/2016  14:20           243�674 vm-xx_20160503_142000.zip
03/05/2016  14:28           212�011 vm-xx_20160503_142806.zip
03/05/2016  14:44           127�759 vm-xx_20160503_144409.zip
               6 fichier(s)        1�025�341 octets
               0 R�p(s)   9�472�864�256 octets libres


```

**Comment by maitrey0da** [comment]
L'archive est bien valide et contient deux fichiers

**Comment by BoboTiG** [comment]
Ça ne serait pas le chemin de Gpg qui serait erroné : C:ombo\\binpg.exe ?

**Comment by maitrey0da** [comment]
Et bien justement, aucune trace de ce binaire ou de répertoire `C:ombo\` sur ma VM

**Comment by BoboTiG** [comment]
Je pense savoir d'où vient ton problème. Dans le fichier de configuration pombo.conf, il faut doubler les antislash pour le chemin du binaire de GPG :
gpg_binary=C:\pombo\bin\gpg.exe
gpg_binary=C:\\pombo\\bin\\gpg.exe

**Comment by maitrey0da** [comment]
Où puis-je trouver ce fichier sur ma machine Windows ?

Merci

**Comment by BoboTiG** [comment]
Il se trouve dans `C:\pombo\pombo.conf`.

**Comment by maitrey0da** [comment]
Ben, je n'ai pas. Je peux le pousser à la main, si il le faut.

```
C:\pombo>dir
 Le volume dans le lecteur C n'a pas de nom.
 Le num�ro de s�rie du volume est BC0D-2D8B

 R�pertoire de C:\pombo

20/04/2016  12:22    <DIR>          bin
03/05/2016  14:42             1�598 clefpublique.asc
20/04/2016  12:22    <DIR>          doc
20/04/2016  12:51                66 pombo
18/05/2015  14:36                65 Pombo - Add IP.bat
18/05/2015  14:36               114 Pombo - Test.bat
18/05/2015  14:36                68 Pombo - Update.bat
18/05/2015  14:36             3�060 pombo.php
20/04/2016  12:22    <DIR>          python
               6 fichier(s)            4�971 octets
               3 R�p(s)   9�465�745�408 octets libres
```

**Comment by BoboTiG** [comment]
Il s'agit d'un fichier système caché ;)

**Comment by maitrey0da** [comment]
Ok, ce fut donc cela. Y'a donc un problème quelque part, pour que le chemin soit correct sans correction manuelle.

Merci @tous

**Comment by zoliaaz** [comment]
Il serait bien d'indiquer lors de l'installation qu'il faut faire ces modifications.
